{% set version = "3.10.1" %}

package:
  name: pytables
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tables/tables-{{ version }}.tar.gz
  sha256: 4aa07ac734b9c037baeaf44aec64ec902ad247f57811b59f30c4e31d31f126cf
  patches:
    - do_not_rely_on_python-blosc2.patch

build:
  number: 3
  entry_points:
    - pt2to3 = tables.scripts.pt2to3:main
    - ptdump = tables.scripts.ptdump:main
    - ptrepack = tables.scripts.ptrepack:main
    - pttree = tables.scripts.pttree:main
  skip: true  # [py<310]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=0.29.32                       # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - python
    - setuptools
    - pip
    - cython >=0.29.32
    - numpy
    - blosc
    - bzip2
    - c-blosc2 >=2.14.4
    - hdf5
    - zlib
  run:
    - python
    - numpy >=1.20.0
    - numexpr
    - packaging
    - py-cpuinfo
    - typing-extensions >=4.4.0

test:
  requires:
    - setuptools
    - pip
  commands:
    - pt2to3 -h
    - ptdump -h
    - ptrepack -h
    - pttree -h
    - pip check

about:
  home: http://www.pytables.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Brings together Python, HDF5 and NumPy to easily handle large amounts of data.
  description: |
    PyTables is a package for managing hierarchical datasets and designed to
    efficiently and easily cope with extremely large amounts of data. PyTables
    is built on top of the HDF5 library, using the Python language and the
    NumPy package.
  doc_url: http://www.pytables.org/
  dev_url: https://github.com/PyTables

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
    - tomkooij
    - scopatz
    - avalentino
